import { IPmEtablissement, NewPmEtablissement } from './pm-etablissement.model';

export const sampleWithRequiredData: IPmEtablissement = {
  id: 'c4cde091-5b24-4e3f-89ab-9729e6966086',
  idEtablissementRPG: 'allegation um er',
  codePartenaireDistributeur: 'all hurtful',
  numeroSiretSiege: 'shrilly gee amidst',
  codeEtat: 'boring beneath cutlet',
  libelleEtat: 'gee aw',
  codeCategoriePersonne: 'meh',
  libelleCategoriePersonne: 'lace',
  codeType: 'verbally hence given',
  dateCreationJuridique: 'certify only scratch',
  dateEtat: 'dead',
  dateFermetureJuridique: 'gosh forenenst',
  codeIDCC: 'whenever yak t-shirt',
  codeTrancheEffectif: 'fooey astride ack',
  libelleTrancheEffectif: 'of desk because',
  dateCessationActivite: 'dimly before',
  dateEffectifOfficiel: 'pitiful pro',
  effectifOfficiel: 'approach',
  codeMotifCessationActivite: 'telescope',
  siret: 'immediately afore notwithstanding',
  codeTypeEtablissement: 'excluding pish',
  libelleEnseigne: 'charter narrowcast almost',
  codeNIC: 'beard angrily after',
};

export const sampleWithPartialData: IPmEtablissement = {
  id: '21e05573-c72b-4b0d-94cc-d64064838ba6',
  idEtablissementRPG: 'pear lumbering than',
  codePartenaireDistributeur: 'commercial whenever downshift',
  numeroSiretSiege: 'arrogantly',
  codeEtat: 'midst than carefree',
  libelleEtat: 'anenst resort',
  codeCategoriePersonne: 'throughout times',
  libelleCategoriePersonne: 'pish',
  codeType: 'gee lazily unnecessarily',
  dateCreationJuridique: 'incline fake',
  dateEtat: 'jubilantly',
  dateFermetureJuridique: 'ha',
  codeIDCC: 'wherever aha',
  codeTrancheEffectif: 'pity for',
  libelleTrancheEffectif: 'account mmm garrote',
  dateCessationActivite: 'yogurt',
  dateEffectifOfficiel: 'ha stool drat',
  effectifOfficiel: 'scented',
  codeMotifCessationActivite: 'dishearten baritone yawningly',
  siret: 'ew knowledgeably boo',
  codeTypeEtablissement: 'window',
  libelleEnseigne: 'obedience pleasing broadly',
  codeNIC: 'disclosure',
};

export const sampleWithFullData: IPmEtablissement = {
  id: 'ba10f239-49bf-4b5c-b9fc-41b46a50b390',
  idEtablissementRPG: 'jury good-natured ironclad',
  codePartenaireDistributeur: 'offset ugh fooey',
  numeroSiretSiege: 'crackle wrongly',
  codeEtat: 'for',
  libelleEtat: 'tight marksman failing',
  codeCategoriePersonne: 'er dress onto',
  libelleCategoriePersonne: 'presume blah what',
  codeType: 'indeed',
  dateCreationJuridique: 'yahoo ew past',
  dateEtat: 'across officially',
  dateFermetureJuridique: 'instantly',
  codeIDCC: 'knowingly painfully',
  codeTrancheEffectif: 'swill',
  libelleTrancheEffectif: 'eek singe',
  dateCessationActivite: 'whoever',
  dateEffectifOfficiel: 'grandson privilege',
  effectifOfficiel: 'likewise',
  codeMotifCessationActivite: 'though finally',
  siret: 'requite courageously',
  codeTypeEtablissement: 'barring promptly',
  libelleEnseigne: 'cinder',
  codeNIC: 'abacus where',
};

export const sampleWithNewData: NewPmEtablissement = {
  idEtablissementRPG: 'illiterate as',
  codePartenaireDistributeur: 'apropos',
  numeroSiretSiege: 'as',
  codeEtat: 'so yet',
  libelleEtat: 'beneath unexpectedly earnest',
  codeCategoriePersonne: 'handsome carpool kookily',
  libelleCategoriePersonne: 'augment calmly',
  codeType: 'sprinkles black-and-white',
  dateCreationJuridique: 'truthfully',
  dateEtat: 'shameful',
  dateFermetureJuridique: 'officially inside',
  codeIDCC: 'intermesh rudely crossly',
  codeTrancheEffectif: 'slowly save',
  libelleTrancheEffectif: 'formal carelessly remarkable',
  dateCessationActivite: 'beside',
  dateEffectifOfficiel: 'ick tank abandoned',
  effectifOfficiel: 'below',
  codeMotifCessationActivite: 'profuse',
  siret: 'woot excluding',
  codeTypeEtablissement: 'oof',
  libelleEnseigne: 'jagged versus',
  codeNIC: 'whoa heartfelt',
  id: null,
};

Object.freeze(sampleWithNewData);
Object.freeze(sampleWithRequiredData);
Object.freeze(sampleWithPartialData);
Object.freeze(sampleWithFullData);
